name: ci

on:
  push:
    branches:
      - main
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.6.0
      - name: Build docker image
        run: |
          docker build . -t hsl
      - name: Push
        run: |
          docker push ghcr.io/WizOfOx/hsl:latest
